config/routes.rb
Rails.application.routes.draw do
  root 'login#new'
  resources :sessions, only: [:create, :destroy]
  get 'auth/google_oauth2/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  resources :login, only: [:new, :create]
  get 'login/block'
  get 'login/ath'
  get 'application/logged'
  resources :hotels, only: [:create, :edit, :show] do
    get 'new', on: :member, as: 'new'
    get 'block', on: :member
    post 'update', on: :member, as: 'update'
  end
  resources :users, only: [:create] do
    get 'new', on: :member
    post 'update', on: :member
    get 'redirect', on: :member
  end
  resources :admin, only: 'show'
  resources :staff, only: [:show, :edit] do
    post 'update', on: :member, as: 'update'
  end
  resources :maid, only: [:show, :edit] do
    get 'delete', on: :member
    get 'cleaning', on: :member
    post 'update', on: :member, as: 'update'
    post 'start', on: :member
    post 'stop', on: :member
    post 'task', on: :member
  end
end

app/views/admin/show.html.erb
<p style = 'text-align:center'>
</p>
<h2>&emsp;Home</h2>
<p style='text-align:right'> 
	<%= link_to 'Create Hotel', new_hotel_path, class: 'btn btn-info'%>&emsp;&emsp;
</p>
<table style="width:40%">
	<tr>
	<th style='width:25%'><th>
	<th style='text-align:center'><h4>Hotels</h4></th>
	<th style='width:25%'><th>
	</tr>
	<%= @hotels.each do |hotel|%>
	<tr>
		<td style='width:25%'><td>
		<td style='text-align:center'>&emsp;<%= link_to hotel.name, {:controller =>'hotels',:action=>'show',:id =>hotel.id},class: 'btn btn-primary btn-block'%></td>
		<td style='width:25%'><td>
	</tr>
	<%end%>
</table><br><br><br><br>