config/routes.rb
Rails.application.routes.draw do
  root 'login#new'
  resources :sessions, only: [:create, :destroy]
  get 'auth/google_oauth2/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  resources :login, only: [:new, :create]
  get 'login/block'
  get 'login/ath'
  get 'application/logged'
  resources :hotels, only: [:create, :edit, :show] do
    get 'new', on: :member, as: 'new'
    get 'block', on: :member
    post 'update', on: :member, as: 'update'
  end
  resources :users, only: [:create] do
    get 'new', on: :member
    post 'update', on: :member
    get 'redirect', on: :member
  end
  resources :admin, only: 'show'
  resources :staff, only: [:show, :edit] do
    post 'update', on: :member, as: 'update'
  end
  resources :maid, only: [:show, :edit] do
    get 'delete', on: :member
    get 'cleaning', on: :member
    post 'update', on: :member, as: 'update'
    post 'start', on: :member
    post 'stop', on: :member
    post 'task', on: :member
  end
end

app/models/hotel.rb
# Hotel Model
class Hotel < ApplicationRecord
  validates :name, presence: { strict: true }, uniqueness: { strict: true }
  validates :no_of_rooms, presence: { strict: true }
  validates :address, presence: { strict: true }
  has_one :image, as: :imageable
  has_many :rooms
  has_many :users
end

app/controllers/hotels_controller.rb
# Hotels Controller
class HotelsController < ApplicationController
  before_action :authorize
  before_action :check
  def new
    check
  end

  def create
    check
    begin
      @hotel = Hotel.create(create_attrs(params))
    rescue StandardError => error
      flash_error(error, 'new')
    else
      image_room_create(params)
      redirect_to admin_path(session[:user_id])
    end
  end

  def edit
    @hotel = Hotel.find(params[:id])
  end

  def update
    check
    begin
      update_hotel(params)
    rescue StandardError => e
      flash_error(e, 'edit')
    else
      flash[:success] = 'Successfully updated!!'
      redirect_to action: 'show', id: params[:id]
    end
  end

  def show
    @hotel = Hotel.find(params[:id])
    @staffs = User.where(hotel_id: params[:id], role_id: Role.staff).find_each
    @maids = User.where(hotel_id: params[:id], role_id: Role.maid).find_each
  end

  def block
    @user = User.find(params[:id])
    if @user.is_active.zero?
      @user.update_attributes!(is_active: true)
    else
      @user.update_attributes!(is_active: false)
    end
    respond_to do |format|
      format.html { redirect_to action: 'show', id: @user.hotel_id }
      format.js
    end
  end

  private

  def flash_error(error, action)
    flash[:error] = error.message
    redirect_to action: action, id: session[:user_id]
  end

  def image_room_create(params)
    @image = Image.create(image_attr(params))
    @hotel.update_attributes!(image_id: @image.id)
    iteration = 101..(params[:hotels][:no_of_rooms].to_i + 100)
    iteration.each do |room_no|
      Room.create(room_attrs(room_no))
    end
    flash[:success] = 'Hotel created!'
  end

  def image_attr(params)
    {
      image: params[:hotels][:imageable],
      imageable_id: @hotel.id,
      imageable_type: 'Hotel'
    }
  end

  def update_img(id)
    {
      imageable_id: id,
      imageable_type: 'Hotel'
    }
  end

  def create_attrs(params)
    { name: params[:hotels][:name],
      no_of_rooms: params[:hotels][:no_of_rooms],
      address: params[:hotels][:address] }
  end

  def room_attrs(room_no)
    { no: room_no,
      hotel_id: @hotel.id,
      estimated_time: '01:00:00',
      status: 'dirty' }
  end

  def update_attrs(params)
    { name: params[:hotels][:name],
      address: params[:hotels][:address] }
  end

  def check
    authorize! :manage, Hotel
  end

  def update_hotel(params)
    Hotel.update(params[:id], update_attrs(params))
    unless params[:hotels][:imageable].nil?
      @image = Image.find_by(update_img(params[:id]))
      @image.update_attributes!(image: params[:hotels][:imageable])
    end
  end
end

app/helpers/hotel_helper.rb
# create helper
module HotelHelper
end

app/views/hotels/_button.html.erb
<% if user.is_active == 0%>
	<%= link_to 'Enable', block_hotel_path(user), remote: true, class: 'btn btn-success'%>
<% else%>
	<%= link_to 'Disable', block_hotel_path(user), remote: true, class: 'btn btn-danger'%>
<%end%>

app/views/hotels/_email.html.erb
<%= link_to user.email, redirect_user_path(user), remote: true%>

app/views/hotels/_image.html.erb
<%= link_to image_tag(user.image.image.url(:thumb)), redirect_user_path(user), remote: true%>

app/views/hotels/_name.html.erb
<%= link_to user.name, redirect_user_path(user), remote: true%>

app/views/hotels/_phone.html.erb
<%= link_to user.phone_no, redirect_user_path(user), remote: true%>

app/views/hotels/block.js.erb
$('#<%=@user.id%>').html("<%= j (render partial: 'button', locals: { user: @user}) %>");

app/views/hotels/edit.html.erb
<body style="text-align:center">
<h2><%=@hotel.name%></h2><br>
<%= form_tag( { :controller => "hotels", :action => "update", :id => params[:id] }, { :multipart => true })do %> 
	<table class='table' style='width:30%' align="center">
	<tr><td style='text-align:center'><b>Hotel name </td><td style='width:60%;text-align:center'><%= text_field(:hotels,:name, value: @hotel.name) %></td></tr>
	<tr><td style='text-align:center'><b>Address </td><td style='width:60%;text-align:center'><%= text_area(:hotels, :address, value: @hotel.address)%></td></tr>
	<tr><td style='text-align:center'><b>Logo </td><td style='width:60%;text-align:center'><%= file_field(:hotels, :imageable)%></td></tr>
	</table><br>
	<p><%= submit_tag "Update", class: 'btn btn-info'%></p>
<% end %><br>
<%= link_to 'Back', {:controller =>'hotels',:action=>'show',:id =>params[:id]}, class: 'btn btn-info'%>
</body>

app/views/hotels/new.html.erb
<body style="text-align:center">
<h2>&emsp;Create Hotel</h2><br>
<%= form_tag({:controller => "hotels", :action => "create"}, { :multipart => true } ) do %> 
	<table class='table' style='width:30%' align="center">
	<tr><td style='text-align:center'><b>Hotel name </td><td style='width:60%;text-align:center'><%= text_field(:hotels,:name) %></td></tr>
	<tr><td style='text-align:center'><b>No of Rooms </td><td style='width:60%;text-align:center'><%= number_field(:hotels, :no_of_rooms)%></td></tr>
	<tr><td style='text-align:center'><b>Address </td><td style='width:60%;text-align:center'><%= text_area(:hotels, :address)%></td></tr>
	<tr><td style='text-align:center'><b>Logo </td><td style='width:60%;text-align:center'><%= file_field(:hotels, :imageable)%></td></tr>
	</table><br>
	<p><%= submit_tag "Create", class: 'btn btn-info'%></p>
<% end %><br>
<%= link_to 'Back', {:controller =>'admin',:action=>'show',:id =>session[:user_id]}, class: 'btn btn-info'%>
</body>

app/views/hotels/show.html.erb
<table class='table' style='width:50%' align='center'>
	<td><h1><%=@hotel.name%></h1></td>
	<td><h1><%= image_tag @hotel.image.image.url(:large) %></h1></td>
</table>
<body style='text-align:center'>
<p style="text-align:right	">
	<%= link_to "Edit", {:controller =>'hotels',:action=>'edit',:id=>params[:id]}%>&emsp;
	<%= link_to "Create User", {:controller =>'users',:action=>'new',:id=>params[:id]}%>&emsp;</p><br>

	<% if @staffs.first !=nil %>
		<h5><b>Staffs</b></h5>
		<table class="table table-bordered" style='width:60%' align='center'>		
			<tr><th style='text-align:center'>Profile</th><th style='text-align:center'>Name</th><th style='text-align:center'>Email</th><th style='text-align:center'>Phone.No</th>
			</tr>
		<% @staffs = User.where(hotel_id: params[:id], role_id: Role.staff).find_each %>
		<% @staffs.each do |staff|%>
			<tr>
				<td id="<%= staff.id%>image">
					<%= render partial: 'image', locals: { user: staff}%>
				</td>
				<td id="<%= staff.id%>name">
					<%= render partial: 'name', locals: { user: staff} %>
				</td>
				<td id="<%= staff.id%>email">
					<%= render partial: 'email', locals: { user: staff} %>
				</td>
				<td id="<%= staff.id%>phone">
					<%= render partial: 'phone', locals: { user: staff} %>
				</td>
				<td style='width:15%;' id="<%= staff.id%>">
					<%= render partial: 'button', locals: { user: staff} %>
		    </td>
			</tr>
		<%end%>
		</table>
	<%else%>
		No staffs available<br>
	<%end%>
	<br>
	<% if @maids.first != nil %>
		<h5><b>Maids</b></h5>
		<table class="table table-bordered" style='width:60%' align='center'>
			<tr><th style='text-align:center'>Profile</th><th style='text-align:center'>Name</th><th style='text-align:center'>Email</th><th style='text-align:center'>Phone.No</th>
			</tr>
			<%= @maids.each do |maid|%>
			<tr>
				<td id="<%= maid.id%>image">
					<%= render partial: 'image', locals: { user: maid}%>
				</td>
				<td id="<%= maid.id%>name">
					<%= render partial: 'name', locals: { user: maid} %>
				</td>
				<td id="<%= maid.id%>email">
					<%= render partial: 'email', locals: { user: maid} %>
				</td>
				<td id="<%= maid.id%>phone">
					<%= render partial: 'phone', locals: { user: maid} %>
				</td>
				<td style='width:15%;' id="<%= maid.id%>">
					<%= render partial: 'button', locals: { user: maid} %>
		    </td>
			</tr>
			<%end%> 
		</table>
	<%else%>
		No maids available
	<%end%>
	<br><br>
	<%= link_to "Back", {:controller =>'admin',:action=>'show',:id=>session[:user_id]},  class: 'btn btn-info btn-small'%><br><br><br><br><br><br>
</body>